#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
yarn check:format ||
(
    echo '🤢🤮🤢🤮 Prettier Check Failed. Run "yarn format", add changes and try commit again. 🤢🤮🤢🤮'
    false;
)

# Check ESLint Standards
yarn lint:src ||
(
        echo '😤🏀👋😤 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again. 😤🏀👋😤'
        false; 
)

# Check tsconfig standards
yarn lint:types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡'
    false;
)


# Check tsconfig standards
# yarn test ||
# (
#     echo '🤡😂❌🤡 One or more Tests failed. Please check logs. 🤡😂❌🤡'
#     false;
# )

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

yarn build ||
(
    echo '❌👷🔨❌ React build failed: View the errors above to see why. ❌👷🔨❌'
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'